@startuml name
title Diagrama de Secuencia - Buscar Noticias
actor Usuario
participant "PaginaPrincipalController" as PPController
participant "NoticiaRepository" as NoticiaRepo

Usuario -> PPController : GET /buscar?q=...
activate PPController
PPController -> NoticiaRepo : createQueryBuilder('n') + filtros
activate NoticiaRepo
NoticiaRepo --> PPController : resultados[]
deactivate NoticiaRepo
PPController --> Usuario : render(pagina_principal/paginaPrincipal.html.twig)
deactivate PPController
@enduml