@startuml Diagrama de Secuencia - Votar Noticia
actor Usuario
participant "NoticiaController" as NoticiaController
participant "NoticiaRepository" as NoticiaRepo
participant "VotoNoticiaRepository" as VotoNoticiaRepo
participant "EntityManagerInterface" as EM

Usuario -> NoticiaController : POST /noticia/{id}/votar\nvotarNoticia(id, Request, NoticiaRepo, VotoRepo, EM)
activate NoticiaController
NoticiaController -> NoticiaController : getUser()
alt not authenticated
NoticiaController --> Usuario : addFlash + redirect(app_iniciar_sesion)
else
NoticiaController -> NoticiaRepo : find(id)
activate NoticiaRepo
NoticiaRepo --> NoticiaController : Noticia|null
deactivate NoticiaRepo
NoticiaController -> VotoNoticiaRepo : findOneBy(['usuario'=>$u,'noticia'=>$n])
activate VotoNoticiaRepo
VotoNoticiaRepo --> NoticiaController : voto|null
deactivate VotoNoticiaRepo
alt existe
NoticiaController -> NoticiaController : setPuntuacion(...) + setFecha(...)
else
NoticiaController -> NoticiaController : new VotoNoticia()
NoticiaController -> EM : persist(VotoNoticia)
activate EM
EM --> NoticiaController : ok
NoticiaController -> EM : flush()
EM --> NoticiaController : ok
deactivate EM
end
NoticiaController --> Usuario : addFlash + redirect(app_pagina_noticia)
end
deactivate NoticiaController
@enduml